id = "java"
name = "Java"
version = "4.0.0"
schema_version = 1
authors = [
    "Valentine Briese <valentinegb@icloud.com>",
    "Samuser107 L.Longheval <samuser107@gmail.com>",
    "Yury Abykhodau <abehodau@gmail.com>",
]
description = "Java support."
repository = "https://github.com/zed-extensions/java"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "a1bbe92a6370bb4c15386735fbda12f2b812a923"

[language_servers.jdtls]
name = "Eclipse JDT Language Server"
language = "Java"
