name: Other Bug
description: A bug related to something else!
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe your bug encounter.
      placeholder: After doing A, B, and then C, I saw X, Y, and Z.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: I expected to see 1, 2, and 3.
    validations:
      required: true
